[package]
name = "offline_license_rs_example"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version="0.4.17", feature = ["release_max_level_warn"] }
simplelog = "0.12.0"

offline_license_rs = { path = "../api" }
hex = "0.4.3"
